package beer.order.service.domain;


public enum BeerOrderStatusEnum {
    NEW, VALIDATED, VALIDATION_EXCEPTION, ALLOCATED, ALLOCATION_EXCEPTION, READY, PENDING_INVENTORY, PICKED_UP, DELIVERY_EXCEPTIONS, DELIVERED, VALIDATION_PENDING, ALLOCATION_PENDING, CANCELLED
}
